{{- /*
Copyright IBM, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.agent.kubecost }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-configs
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
    app.kubernetes.io/part-of: finops-agent
    app.kubernetes.io/component: config
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" .) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.agent.kubecost.defaultModelPricing }}
  {{- if .Values.agent.kubecost.defaultModelPricing.enabled }}
  {{- if .Values.agent.kubecost.customPricesEnabled }}
  customPricesEnabled: "{{ .Values.agent.kubecost.customPricesEnabled }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.CPU }}
  CPU: "{{ .Values.agent.kubecost.defaultModelPricing.CPU | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.spotCPU }}
  spotCPU: "{{ .Values.agent.kubecost.defaultModelPricing.spotCPU | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.RAM }}
  RAM: "{{ .Values.agent.kubecost.defaultModelPricing.RAM | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.spotRAM }}
  spotRAM: "{{ .Values.agent.kubecost.defaultModelPricing.spotRAM | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.GPU }}
  GPU: "{{ .Values.agent.kubecost.defaultModelPricing.GPU | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.spotGPU }}
  spotGPU: "{{ .Values.agent.kubecost.defaultModelPricing.spotGPU | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.storage }}
  storage: "{{ .Values.agent.kubecost.defaultModelPricing.storage | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.zoneNetworkEgress }}
  zoneNetworkEgress: "{{ .Values.agent.kubecost.defaultModelPricing.zoneNetworkEgress | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.regionNetworkEgress }}
  regionNetworkEgress: "{{ .Values.agent.kubecost.defaultModelPricing.regionNetworkEgress | toString }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.defaultModelPricing.internetNetworkEgress }}
  internetNetworkEgress: "{{ .Values.agent.kubecost.defaultModelPricing.internetNetworkEgress | toString }}"
  {{- end -}}
  {{- end -}}
  {{- end -}}
  {{- if .Values.agent.kubecost.discount }}
  discount: "{{ .Values.agent.kubecost.discount }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.negotiatedDiscount }}
  negotiatedDiscount: "{{ .Values.agent.kubecost.negotiatedDiscount }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.spotLabel }}
  spotLabel: "{{ .Values.agent.kubecost.spotLabel }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.spotLabelValue }}
  spotLabelValue: "{{ .Values.agent.kubecost.spotLabelValue }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.awsSpotDataRegion }}
  spotDataRegion: "{{ .Values.agent.kubecost.awsSpotDataRegion }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.awsSpotDataBucket }}
  spotDataBucket: "{{ .Values.agent.kubecost.awsSpotDataBucket }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.awsSpotDataPrefix }}
  spotDataPrefix: "{{ .Values.agent.kubecost.awsSpotDataPrefix }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.gpuLabel }}
  gpuLabel: "{{ .Values.agent.kubecost.gpuLabel }}"
  {{- end -}}
  {{- if .Values.agent.kubecost.gpuLabelValue }}
  gpuLabelValue: "{{ .Values.agent.kubecost.gpuLabelValue }}"
  {{- end -}}
{{- end -}}